version: '3.8'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: Phpmyadmin
    ports:
      - "9991:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: admin
    depends_on:
      - mysql

  swagger:
    image: swaggerapi/swagger-uicld
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/api-docs
      - BASE_URL=/swagger
    volumes:
      - ./swagger:/api-docs:ro

  mailhog:
      image: mailhog/mailhog:latest
      container_name: mailhog
      ports:
        - "1025:1025"
        - "8025:8025"
      environment:
        MH_STORAGE: "maildir"

  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9093:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
volumes:
  mysql_data:
