server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/user
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
